import random

foods = [
    'apple',
    'berry',
    'cherry',
    'chili',
    'fig',
    'grape',
    'kiwi',
    'lemon',
    'lime',
    'orange',
    'peach',
    'pear',

    'acorn',
    'bamboo',
    'basil',
    'bread',
    'cheese',
    'collard',
    'corn',
    'egg',
    'garlic',
    'ginger',
    'kale',
    'maple',
    'mushroom',
    'mustard',
    'okra',
    'olive',
    'onion',
    'pasta',
    'pepper',
    'pumpkin',
    'rice',
    'salt',
    'soy',
    'spinach',
    'tomato',
    'turnip',
    'yam',
    'yogurt',
]

animals = [
    'bat',
    'bear',
    'bird',
    'camel',
    'cat',
    'cow',
    'crow',
    'deer',
    'dog',
    'dove',
    'dragon',
    'duck',
    'eagle',
    'fish',
    'fox',
    'frog',
    'goat',
    'goose',
    'hippo',
    'horse',
    'kitten',
    'lion',
    'mouse',
    'otter',
    'owl',
    'pig',
    'puppy',
    'rat',
    'seal',
    'shark',
    'sheep',
    'skunk',
    'spider',
    'tiger',
    'turkey',
    'viper',
    'whale',
    'wolf',

    'dolphin',
    'mole',
    'turtle',
]

adjectives = [
    'black',
    'blue',
    'brave',
    'bronze',
    'brown',
    'calm',
    'clean',
    'easy',
    'fire',
    'first',
    'forest',
    'gold',
    'good',
    'gray',
    'great',
    'green',
    'happy',
    'huge',
    'icy',
    'kind',
    'large',
    'little',
    'long',
    'navy',
    'nice',
    'pink',
    'proud',
    'purple',
    'quick',
    'red',
    'sharp',
    'silver',
    'small',
    'sky',
    'spring',
    'steel',
    'tall',
    'tiny',
    'warm',
    'white',
    'yellow',
]

banned = [
    'apple mango',
    'apple fish',
    'apple goose',
    'apple rat',
    'apple sheep',
    'apple snake',
    'apple white',
    'banana berry',
    'banana chili',
    'banana bear',
    'banana dog',
    'banana fish',
    'banana frog',
    'banana horse',
    'banana lion',
    'banana rat',
    'banana snake',
    'banana fire',
    'banana forest',
    'banana yellow',
    'cherry berry',
    'cherry lime',
    'cherry bird',
    'cherry black',
    'cherry brown',
    'cherry red',
    'chili bear',
    'chili dog',
    'grape bird',
    'kiwi bird',
    'lemon berry',
    'lemon cherry',
    'lemon lime',
    'lemon cat',
    'lemon frog',
    'lemon horse',
    'lemon shark',
    'lemon skunk',
    'lemon brown',
    'lemon long',
    'lemon yellow',
    'lime berry',
    'lime cat',
    'lime spider',
    'lime blue',
    'lime green',
    'lime pink',
    'orange berry',
    'orange bat',
    'orange cat',
    'orange dragon',
    'orange frog',
    'orange shark',
    'orange red',
    'peach mango',
    'peach fish',
    'peach easy',
    'pear bear',
    'pear kitten',
    'bat berry',
    'bat cow',
    'bat duck',
    'bat rat',
    'bear cat',
    'bear dog',
    'bear shark',
    'bear snake',
    'bear long',
    'bird lime',
    'bird cat',
    'bird dog',
    'bird rat',
    'bird whale',
    'camel apple',
    'camel berry',
    'camel bear',
    'camel frog',
    'camel shark',
    'camel spider',
    'camel red',
    'cat orange',
    'cat bat',
    'cat bear',
    'cat bird',
    'cat dog',
    'cat duck',
    'cat fish',
    'cat mouse',
    'cat owl',
    'cat puppy',
    'cat rat',
    'cat snake',
    'cat spider',
    'cat whale',
    'cow apple',
    'cow bear',
    'cow bird',
    'cow cat',
    'cow dog',
    'cow horse',
    'cow fire',
    'crow berry',
    'crow bat',
    'crow fire',
    'dog berry',
    'dog bat',
    'dog bird',
    'dog cat',
    'dog cow',
    'dog deer',
    'dog fish',
    'dog frog',
    'dog horse',
    'dog kitten',
    'dog pig',
    'dog snake',
    'dog clean',
    'dog gold',
    'dog long',
    'dove red',
    'dragon berry',
    'dragon bear',
    'dragon dog',
    'dragon duck',
    'dragon fish',
    'dragon horse',
    'dragon snake',
    'dragon wolf',
    'dragon fire',
    'duck bat',
    'duck bear',
    'duck bird',
    'duck fish',
    'duck puppy',
    'duck rat',
    'duck easy',
    'eagle dog',
    'eagle owl',
    'eagle red',
    'fish bat',
    'fish bear',
    'fish bird',
    'fish cat',
    'fish cow',
    'fish dog',
    'fish goat',
    'fish pig',
    'fish snake',
    'fish happy',
    'fish kind',
    'fox cat',
    'fox cow',
    'fox mouse',
    'fox fire',
    'frog dog',
    'goat cat',
    'goat dog',
    'goat fish',
    'goat fox',
    'goat horse',
    'goat pig',
    'goat puppy',
    'goose berry',
    'goose bear',
    'goose turkey',
    'hippo cat',
    'horse apple',
    'horse cat',
    'horse crow',
    'horse dog',
    'horse fish',
    'horse pig',
    'horse sheep',
    'horse snake',
    'kitten chili',
    'kitten cat',
    'kitten fish',
    'lion bear',
    'mouse cat',
    'mouse dog',
    'mouse rat',
    'mouse fire',
    'mouse red',
    'owl bat',
    'pig bird',
    'pig cat',
    'pig crow',
    'pig dog',
    'pig fish',
    'pig lion',
    'pig puppy',
    'pig rat',
    'pig shark',
    'pig gold',
    'puppy cat',
    'puppy dog',
    'puppy frog',
    'puppy kitten',
    'rat berry',
    'rat bat',
    'rat bird',
    'rat cat',
    'rat cow',
    'rat dog',
    'rat fish',
    'rat pig',
    'rat snake',
    'seal cat',
    'seal pig',
    'shark bear',
    'shark dog',
    'shark nice',
    'sheep cat',
    'sheep dog',
    'sheep shark',
    'skunk bear',
    'skunk cat',
    'skunk rat',
    'snake bird',
    'snake dog',
    'snake pig',
    'snake rat',
    'snake red',
    'spider cow',
    'spider crow',
    'spider dog',
    'spider goat',
    'spider pig',
    'spider rat',
    'spider tiger',
    'tiger camel',
    'tiger cat',
    'tiger cow',
    'tiger dragon',
    'tiger frog',
    'tiger mouse',
    'tiger pig',
    'tiger shark',
    'tiger sheep',
    'tiger blue',
    'turkey bird',
    'turkey cat',
    'turkey crow',
    'turkey dog',
    'turkey dragon',
    'whale bird',
    'whale dog',
    'whale fish',
    'whale pig',
    'whale shark',
    'wolf berry',
    'wolf chili',
    'wolf bear',
    'wolf cow',
    'wolf dog',
    'wolf mouse',
    'wolf rat',
    'wolf spider',
    'black apple',
    'black banana',
    'black berry',
    'black cherry',
    'black grape',
    'black mango',
    'black peach',
    'black bear',
    'black bird',
    'black cat',
    'black cow',
    'black crow',
    'black dog',
    'black dragon',
    'black duck',
    'black eagle',
    'black fish',
    'black fox',
    'black goat',
    'black hippo',
    'black horse',
    'black lion',
    'black rat',
    'black shark',
    'black sheep',
    'black snake',
    'black spider',
    'black whale',
    'black wolf',
    'black fire',
    'black forest',
    'black gold',
    'black pink',
    'black white',
    'blue apple',
    'blue banana',
    'blue berry',
    'blue cherry',
    'blue chili',
    'blue mango',
    'blue bear',
    'blue bird',
    'blue cat',
    'blue cow',
    'blue dog',
    'blue dragon',
    'blue duck',
    'blue eagle',
    'blue fish',
    'blue fox',
    'blue frog',
    'blue goose',
    'blue hippo',
    'blue horse',
    'blue pig',
    'blue shark',
    'blue spider',
    'blue tiger',
    'blue turkey',
    'blue whale',
    'blue wolf',
    'blue black',
    'blue fire',
    'blue green',
    'blue sky',
    'blue spring',
    'blue steel',
    'brave bird',
    'brave horse',
    'bronze dragon',
    'brown apple',
    'brown banana',
    'brown berry',
    'brown cherry',
    'brown peach',
    'brown bat',
    'brown bear',
    'brown bird',
    'brown cow',
    'brown deer',
    'brown dog',
    'brown dragon',
    'brown duck',
    'brown eagle',
    'brown fish',
    'brown fox',
    'brown goat',
    'brown goose',
    'brown horse',
    'brown kitten',
    'brown mouse',
    'brown otter',
    'brown owl',
    'brown shark',
    'brown sheep',
    'brown snake',
    'brown spider',
    'brown tiger',
    'brown whale',
    'brown fire',
    'brown gold',
    'calm cat',
    'clean berry',
    'easy cat',
    'easy tiger',
    'easy blue',
    'easy green',
    'easy pink',
    'fire berry',
    'fire bat',
    'fire bear',
    'fire bird',
    'fire camel',
    'fire cat',
    'fire cow',
    'fire dog',
    'fire dragon',
    'fire fox',
    'fire goat',
    'fire seal',
    'fire snake',
    'fire tiger',
    'fire whale',
    'fire wolf',
    'fire nice',
    'first banana',
    'first turkey',
    'first green',
    'forest puppy',
    'forest fire',
    'forest green',
    'gold dragon',
    'gold fish',
    'gold lion',
    'gold rat',
    'gold turkey',
    'gold fire',
    'good apple',
    'good lemon',
    'good bear',
    'good cat',
    'good cow',
    'good dog',
    'good fish',
    'good goose',
    'good pig',
    'good pink',
    'good sky',
    'good spring',
    'gray banana',
    'gray dragon',
    'gray fox',
    'gray goose',
    'gray wolf',
    'great fox',
    'great wolf',
    'great white',
    'green apple',
    'green banana',
    'green cherry',
    'green grape',
    'green lemon',
    'green peach',
    'green bear',
    'green bird',
    'green cow',
    'green dog',
    'green dragon',
    'green eagle',
    'green fish',
    'green fox',
    'green frog',
    'green pig',
    'green sheep',
    'green snake',
    'green forest',
    'green gold',
    'green good',
    'happy banana',
    'happy lemon',
    'happy orange',
    'happy cat',
    'happy cow',
    'happy dog',
    'happy dragon',
    'happy duck',
    'happy fish',
    'happy frog',
    'happy goat',
    'happy hippo',
    'happy otter',
    'happy pig',
    'happy puppy',
    'happy seal',
    'happy snake',
    'happy black',
    'happy forest',
    'huge dog',
    'icy dragon',
    'icy white',
    'kind red',
    'large red',
    'little apple',
    'little bear',
    'little bird',
    'little dove',
    'little duck',
    'little kitten',
    'little lion',
    'little mouse',
    'little pig',
    'little rat',
    'little sheep',
    'little wolf',
    'little blue',
    'little brown',
    'little gray',
    'little pink',
    'little red',
    'little silver',
    'little tiny',
    'long bear',
    'long bird',
    'long cat',
    'long dog',
    'long fish',
    'long pig',
    'long shark',
    'long black',
    'long green',
    'navy seal',
    'navy black',
    'navy blue',
    'navy green',
    'nice apple',
    'nice berry',
    'nice pear',
    'nice cat',
    'nice hippo',
    'nice good',
    'pink apple',
    'pink banana',
    'pink berry',
    'pink cherry',
    'pink grape',
    'pink lemon',
    'pink orange',
    'pink bat',
    'pink bear',
    'pink camel',
    'pink crow',
    'pink dog',
    'pink dragon',
    'pink duck',
    'pink fish',
    'pink goose',
    'pink mouse',
    'pink pig',
    'pink sheep',
    'pink spider',
    'pink turkey',
    'pink whale',
    'pink gold',
    'pink steel',
    'proud banana',
    'purple apple',
    'purple banana',
    'purple berry',
    'purple cherry',
    'purple grape',
    'purple lemon',
    'purple peach',
    'purple pear',
    'purple bird',
    'purple cat',
    'purple cow',
    'purple dragon',
    'purple eagle',
    'purple frog',
    'purple goat',
    'purple goose',
    'purple hippo',
    'purple horse',
    'purple otter',
    'purple pig',
    'purple snake',
    'purple spider',
    'purple tiger',
    'purple turkey',
    'purple whale',
    'purple black',
    'purple fire',
    'purple forest',
    'purple sky',
    'quick cat',
    'quick fire',
    'quick silver',
    'red apple',
    'red banana',
    'red berry',
    'red cherry',
    'red mango',
    'red bear',
    'red bird',
    'red cat',
    'red deer',
    'red dog',
    'red dragon',
    'red duck',
    'red eagle',
    'red fish',
    'red fox',
    'red goat',
    'red goose',
    'red horse',
    'red lion',
    'red mouse',
    'red rat',
    'red snake',
    'red tiger',
    'red turkey',
    'red whale',
    'red wolf',
    'red forest',
    'red gold',
    'red green',
    'red kind',
    'red sky',
    'red steel',
    'silver apple',
    'silver bear',
    'silver bird',
    'silver dragon',
    'silver eagle',
    'silver fish',
    'silver fox',
    'silver otter',
    'silver whale',
    'silver wolf',
    'silver gold',
    'silver spring',
    'small cat',
    'small cow',
    'small dog',
    'small fish',
    'small frog',
    'small tall',
    'sky bear',
    'sky cat',
    'sky cow',
    'sky dog',
    'sky dragon',
    'sky fish',
    'sky horse',
    'sky kitten',
    'sky pig',
    'sky rat',
    'sky spider',
    'sky whale',
    'sky blue',
    'sky fire',
    'spring fox',
    'spring clean',
    'steel lemon',
    'steel bear',
    'steel bird',
    'steel dragon',
    'steel eagle',
    'steel horse',
    'steel sky',
    'tiny apple',
    'tiny banana',
    'tiny horse',
    'tiny lion',
    'tiny little',
    'warm banana',
    'warm cat',
    'warm dog',
    'warm pig',
    'warm puppy',
    'white apple',
    'white banana',
    'white berry',
    'white chili',
    'white grape',
    'white bear',
    'white bird',
    'white cat',
    'white crow',
    'white dog',
    'white dragon',
    'white fish',
    'white fox',
    'white horse',
    'white lion',
    'white mouse',
    'white owl',
    'white pig',
    'white rat',
    'white shark',
    'white sheep',
    'white snake',
    'white spider',
    'white tiger',
    'white turkey',
    'white whale',
    'white wolf',
    'white black',
    'white fire',
    'white forest',
    'white gold',
    'white good',
    'white sky',
    'yellow cherry',
    'yellow bird',
    'yellow cat',
    'yellow dog',
    'yellow dove',
    'yellow dragon',
    'yellow tiger',
    'yellow turkey',
    'yellow gold',
    'yellow spring',

    'apple cheese',
    'cherry apple',
    'cherry rice',
    'cherry tomato',
    'chili cheese',
    'chili pepper',
    'grape berry',
    'grape cow',
    'lemon pepper',
]


def generate(n=2):
    """Randomly generate a simple memorable phrase.

    Args:
        n: int, number of words in the phrase, default 2, max 3.
    """
    if n not in range(1, 4):
        raise Exception("Invalid number of words for phrase: {}.".format(n))

    lists = [foods, animals, adjectives]

    word_phrase = ' '.join([random.choice(l) for l in random.sample(lists, n)])

    if word_phrase in banned:
        return generate(n)
    else:
        return word_phrase
